### ISSUE TITLE
Add kotlin's coroutines with rxjava2

### ISSUE THREAD

**Issue by stream1984** [vert-x3/vertx-rx#100]
Hi i am interesting in kotlin's coroutines to wrapper rxjava2 so we can make rxjava2 program in sync way.
Shall we create module for this project, or make other new repo?

**Comment by vietj** [comment]
@stream1984 I believe there is already a library doing that in the kotlin coroutine library project, besides I think it is something out of the scope of the vertx stack

**Comment by vietj** [comment]
have you checked https://github.com/Kotlin/kotlinx.coroutines/tree/master/reactive/kotlinx-coroutines-rx2 ?

**Comment by stream1984** [comment]
Yes, i have checked kotlinx-coroutines-rx2.
That would be great give some examples kotlinx-coroutines-rx2 with vertx-rx

**Comment by vietj** [comment]
we'll do that in the examples repository. I've also added a note that vertx kotlin coroutine works well with rxjava in the documentation.
