### ISSUE TITLE
Signal the complete callback when a MessageConsumer is unregistered

### ISSUE THREAD

**Issue by erickj** [vert-x3/vertx-rx#102]
Hi,

I just started looking at the new io.vertx.reactivex package for its rxjava2 support. I've put together a little Hello world for myself, but can't seem to get Observable subscription's created via MessageConsumer#toObservable to trigger their onComplete. See an example here:

https://gist.github.com/erickj/42198aa0041ac1e1be0a54736bca419f

(this is using vertx-rx 8a1b87cc and vertx-core 3.4.2)

At line 41 in the example above at `consumer.unregister()`, I'd expect to see "consumer:complete" printed, but it seems that it skips calling the ReadStream#endHandler here's the relevant portion of the stack:

  [1] io.vertx.core.eventbus.impl.HandlerRegistration.doUnregister (HandlerRegistration.java:125)
  [2] io.vertx.core.eventbus.impl.HandlerRegistration.unregister (HandlerRegistration.java:113)
  [3] io.vertx.core.eventbus.impl.HandlerRegistration.unregister (HandlerRegistration.java:103)
  [4] io.vertx.reactivex.core.eventbus.MessageConsumer.unregister (MessageConsumer.java:183)
  [5] io.vos.vertx.HelloRx.lambda$runRx$3 (HelloRx.java:41)

HandlerRegistration#doUnregister is called with false for `callEndHandler`. This bypasses the endHandler registered on the ObservableReadStream so that `observer.onComplete` is never called, here:

https://github.com/vert-x3/vertx-rx/blob/master/rxjava2/src/main/java/io/vertx/reactivex/core/impl/ObservableReadStream.java#L50-L53

I've tried a few ways of triggering the onComplete handler, including disposing the subscription, but after reading ObservableReadStream now see that dispose effectively unsets all of the handlers that trigger observer callbacks.

Am I missing something?

**Comment by vietj** [comment]
I think this was done on purpose, because if you unregister the consumer it means that you are taking this action

**Comment by erickj** [comment]
So how do you trigger the `observer.onComplete` call?

**Comment by vietj** [comment]
I don't think it's ever called as the endHandler is meaningless with event bus as it never stops.

**Comment by erickj** [comment]
Ok thank you

**Comment by vietj** [comment]
Actually I would like to revisit this item to implement the behavior you are describing

**Comment by vietj** [comment]
This would be helpful for RxJava but also for Kotlin channel adapters

**Comment by vietj** [comment]
fixed as side effect of https://github.com/eclipse/vert.x/pull/2105 - just added a test
