### ISSUE TITLE
Missing calls to RxJavaSchedulersHook.onSchedule when using RxHelper.schedulerHook

### ISSUE THREAD

**Issue by timove** [vert-x3/vertx-rx#11]
Hi vertx-rx team!

In plain rxjava RxJavaSchedulersHook.onSchedule gets called by ScheduledAction.scheduleActual(...). This hook is important, to allow for applications to transfer ThreadLocal values from the scheduling thread to the executing thread.

When using RxHelper.schedulerHook (to have Scheduler.io() operations run in a vert.x worker thread) the calls to the RxJavaSchedulersHook.onSchedule method never happen. I assume, those need to be added to the ContextScheduler.WorkerImpl.schedule(...) methods.

Best regards,
Timo

**Comment by purplefox** [comment]
Julien @vietj -  what's your option on this?

**Comment by vietj** [comment]
I think we should have a test showing the issue and implement it.
