### ISSUE TITLE
Expose WriteStream as Observer

### ISSUE THREAD

**Issue by nicolaferraro** [vert-x3/vertx-rx#115]
Following the vertx rx-java 2 documentation, it seems there's a easy way to transform a read stream into a flowable, using the `FlowableHelper.toFlowable` utility method, but **nothing for write streams**.

The documentation uses the following example to send data from rx-java to the eventbus:
```
observable.
    buffer(1, TimeUnit.SECONDS).
    map(samples -> samples.
        stream().
        collect(Collectors.averagingDouble(d -> d))).
    subscribe(heat -> {
      vertx.eventBus().send("news-feed", "Current heat is " + heat);
    });
```

But if you send messages to the eventbus in the `subscribe` method, you cannot handle backpressure correctly (I've an example that hangs if I send too many messages, but I don't get any exception to confirm that backpressure is the only problem).

Is there a way to turn a write stream into a `Observer`?
E.g.:
```
Observer<X> obs = FlowableHelper.toObserver(vertx.eventBus().publisher("address"));
observable.subscribe(obs);
```

Or something similar..

**Comment by vietj** [comment]
I believe that's something we should have.

**Comment by nicolaferraro** [comment]
I go back to my original proposal ;-)

```
Subscriber<X> subs = FlowableHelper.toSubscriber(vertx.eventBus().publisher("address"));
flowable.subscribe(subs);
```

According to [rx-java 2 doc](http://reactivex.io/RxJava/2.x/javadoc/io/reactivex/Flowable.html), a `Flowable` wants a reactive streams `Subscriber` or a `FlowableSubscriber`, while a `Observer` can be used with a `Observable`, but it's not [backpressure-aware](http://reactivex.io/RxJava/2.x/javadoc/io/reactivex/Observable.html).

Is there already something in `vertx-reactrive-streams` to convert a write stream into a subscriber?

**Comment by vietj** [comment]
with vertx-reactive-streams you would need an extra `Pump`:

```
    ReactiveReadStream<Buffer> rrs = ReactiveReadStream.readStream();

    // Subscribe the read stream to the publisher
    otherPublisher.subscribe(rrs);

    // Pump from the read stream to the http response
    Pump pump = Pump.pump(rrs, response);

    pump.start();
```

**Comment by codepitbull** [comment]
I strongly believe we should base the RxJava2 stuff on top of our ReactiveStreams implementation.
RxJava2 is completely built around the idea of Reactive Streams and integration comes way more fluent.
That's what I did for the upcoming streams support in vertx-lang-scala.
I first adapt WriteStream/ReadStream to Reactive Streams and then connect RxJava 2 (https://github.com/codepitbull/vertx-streams/blob/master/src/test/scala/io/vertx/lang/scala/streams/RxJava2IntegrationTest.scala). 
This feels way more natural and there is no way of missing backpressure.

**Comment by vietj** [comment]
the actual Reactive Streams implementation uses a lot runOnContext which can create timing issues, (I tried in the past and it was not possible to have everything working correctly). So I'm not really in favor of this move.

My opinion is that we should rather in the future extend Vert.x read stream to support a request based model in addition of pause/resume, something like:

```
interface ReadStream<T> {
   // Usual operations
   void pause();
   void resume();
   //
   void request(int amount); // Request n items
}
```

which would allow to ease the integration with RS or RxJava2. It aims also to solve the problem that current adapters (vertx-reactive-streams, vertx-rxjava2) have to maintain an extra queue of items between the subscriber and the read stream.

**Comment by vietj** [comment]
actually what you said makes sense but in practice we would several queues holding items, the read stream implementation, the vertx-reactive-streams and potentially the rxjava2 when it needs one (usually it tries to avoid intermediary queues using fusion http://akarnokd.blogspot.fr/2016/03/operator-fusion-part-1.html)
