### ISSUE TITLE
RxJava2 non-rxified Vertx Web client 

### ISSUE THREAD

**Issue by kpatel311** [vert-x3/vertx-rx#116]
Noob question. I previously used RxHelper.observableHandler in rxjava with the non-rxified Vertx Web Client to convert between handlers and observables like so:
```
        val observable = RxHelper.observableHandler<AsyncResult<HttpResponse<Buffer>>>()
       ...
        client
                .get("example.com", "/some/endpoint")
                .addQueryParam("token", "token")
                .send(observable.toHandler())

        return observable.asObservable()
```
I am having trouble doing the same operation in rxjava2. Is this supported at all?

**Comment by vietj** [comment]
I think you can use the rxified API and use `rxSend` that will give you a `Single<HttpResponse<Buffer>>` and then eventually convert it to another RxJava type

**Comment by vietj** [comment]
marked as invalid, as this is a question

**Comment by kpatel311** [comment]
Due to circumstances beyond my control, I can't use the rxified API. Does rxjava2 provide some sort of helper that I'm missing that can be used to convert between handlers and observables for use with the non-rxified Vertx API?
