### ISSUE TITLE
add methods for byte arrays to rx lib

### ISSUE THREAD

**Issue by njleonzhang** [vert-x3/vertx-rx#121]
according to this [thread](https://groups.google.com/forum/#!topic/vertx/AhRW62sOAu0), methods for byte arrays are lacked in rx library. This cause lots of migration effort. Any plan to add this lost methods?

```
import io.vertx.core.buffer.Buffer
buffer.getBytes()
.....
Buffer.buffer(bytes); // Byte []
```

---> 

```
import io.vertx.reactivex.core.buffer.Buffer
buffer.getDelegate().getBytes()
.....
buffer = Buffer(io.vertx.core.buffer.Buffer.buffer(bytes))
```

**Comment by tsegismont** [comment]
These methods will be present in 3.6
