### ISSUE TITLE
AutoCloseable automatic closing at unsubscription time 

### ISSUE THREAD

**Issue by vietj** [vert-x3/vertx-rx#122]
The idea is to handle specially resources that implement `closable` to relieve the user from closing them at the end of the interaction, e.g:

```
Single<SQLConnection> single = client.rxGetConnection();
single.subscribe(conn -> {}, err -> {});
```

When the `Single` is disposed, close the `SQLConnection` on behalf of the user if that user has not closed it before.

**Comment by krishnarb3** [comment]
Hello, I would like to take up this issue. Can you brief me on how I should go about it.

**Comment by vietj** [comment]
you can try to implement it class `AsyncResultSingle`, when the `dispose` flag is set to false and the `T` instance returned b y `ar.result()` implements `AutoCloseable` then it should be closed.

**Comment by vietj** [comment]
it should be tested and implemented for RxJava 1  and RxJava 2 with various tests

**Comment by krishnarb3** [comment]
Thank you, I'll get right into it.

**Comment by krishnarb3** [comment]
Which class should I implement in and test for RxJava 1?

**Comment by vietj** [comment]
For the record, here is how it should work with RxJava 1:

```
    Future<AutoCloseable> fut1 = Future.future();
    SingleOnSubscribeAdapter<AutoCloseable> adapter = new SingleOnSubscribeAdapter<>(fut1::setHandler);
    Single<AutoCloseable> single = Single.create(adapter);
    single = single.doOnUnsubscribe(() -> {
      try {
        adapter.value().close();
      } catch (Exception e) {
        e.printStackTrace();
      }
    });

    AtomicBoolean closed = new AtomicBoolean();
    AutoCloseable item = () -> closed.set(true);

    Future<String> fut2 = Future.future();
    Single<String> single2 = Single.create(new SingleOnSubscribeAdapter<>(fut2::setHandler));

    AtomicBoolean completed = new AtomicBoolean();
    single.flatMap(c -> single2).subscribe(ok -> {
      completed.set(true);
      assertFalse(closed.get());
    });

    assertFalse(completed.get());
    fut1.complete(item);
    assertFalse(completed.get());
    assertFalse(closed.get());
    fut2.complete("whatever");
    assertTrue(completed.get());
    assertTrue(closed.get());
```

given that we modify `SingleOnSubscribeAdapter` this way:

```
public class SingleOnSubscribeAdapter<T> implements Single.OnSubscribe<T> {

  protected final Consumer<Handler<AsyncResult<T>>> consumer;
  private volatile T value;

  public SingleOnSubscribeAdapter(Consumer<Handler<AsyncResult<T>>> consumer) {
    this.consumer = consumer;
  }

  // OnSubscribe

  public T value() {
    return value;
  }

  /**
   * Subscription
   */
  @Override
  public void call(SingleSubscriber<? super T> sub) {
    consumer.accept(ar -> {
      if (!sub.isUnsubscribed()) {
        if (ar.succeeded()) {
          sub.onSuccess(value = ar.result());
        } else {
          sub.onError(ar.cause());
        }
      }
    });
  }
}
```

**Comment by krishnarb3** [comment]
Sorry for the delay, I'll try to get this done by today.

**Comment by krishnarb3** [comment]
@vietj Please correct me if I am wrong, we are supposed to close the single if it's type parameter is AutoCloseable right?
So this code:
``` SingleOnSubscribeAdapter<AutoCloseable> adapter = new SingleOnSubscribeAdapter<>(fut1::setHandler);
    Single<AutoCloseable> single = Single.create(adapter);
    single = single.doOnUnsubscribe(() -> {
      try {
        adapter.value().close();
      } catch (Exception e) {
        e.printStackTrace();
      }
    });
```
should be made automatic (Closing the adapter on unsubscribe) right?
The rest of the code is to illustrate testing?
Also regarding my PR, can you explain a bit more on how I should use the codegen project with vertx-rx to detect type at runtime?

**Comment by vietj** [comment]
we need to add in codegen a boolean "autoCloseable" on `ClassTypeInfo` first, just have a look there first to make up your mind

**Comment by vietj** [comment]
the feature can be implemented for RxJava1 (as shown in the example) but can't be in RxJava2 that has different way to do things.
