### ISSUE TITLE
Log runtime errors in AsyncResultSingle

### ISSUE THREAD

**Issue by arr-ee** [vert-x3/vertx-rx#124]
Related to this: https://github.com/vert-x3/vertx-rx/blame/master/rx-java2/src/main/java/io/vertx/reactivex/core/impl/AsyncResultSingle.java#L48-L49

Currently vertx swallows exceptions occurring upstream. This makes debugging quite frustrating since it looks like function just halts, even though in reality there was an exception.

I wonder if it’d be acceptable to at least add a logger call there if we’re not supposed to fail subscribers?

Thanks.

**Comment by vietj** [comment]
agreed, a patch is welcome

**Comment by HighKo** [comment]
I can only agree. An empty catch block is really scary.

**Comment by ninoraubaum** [comment]
Took me hours to figure out why the database (vertx-mysql-postgresql-client) isn't responding. Actually the exception was ignored. Would be great if this could be changed.

**Comment by vietj** [comment]
we will fix it in 3.5.1, I was expecting a patch for this trivial issue to fix but did not get any
