### ISSUE TITLE
Observable<HttpClientResponse> should end() on subscribe()

### ISSUE THREAD

**Issue by dctr** [vert-x3/vertx-rx#13]
Hello vert-rx,

a code sample in the official examples repo is as follows:

```java
    public void httpClientRequest(Vertx vertx) {
        HttpClient client = vertx.createHttpClient(new HttpClientOptions());
        HttpClientRequest request = client.request(HttpMethod.GET, 8080, "localhost", "/the_uri");
        request.toObservable().subscribe(response -> {
                // Process the response
        }, error -> {
                // Could not connect
        });
        request.end();
    }
```

In the sample, the subscribe() on the observable is analogous to the handler(...) in the non-rx world. However, in my opinion, the subscribe itself should trigger the end() by itself. This was the case with mod-rxvertx in Vert.x 2.

My usecase (simplified) is/was a function as follows:

```java
public Observable<JsonObject> requestJsonResource(HttpClient client, String url) {
    return client.get(url).toObservable().someMapReduceMagicToTransformResponseToJson(...);
}
```

The caller of the function then called subscribe() and got an Observable of a JsonObject. Now he would have to end the request, but as the request is managed under the hood, this is not possible.

I then tried doing the following

```java
    ...
    HttpClientRequest request = client.get(url);
    return request.toObservable().doOnSubscribe(request::end).someTransformation(...)
```

But as the doOnSubscribe triggers before the subscription happens, I get an exception that no handlers for the request which is about to being send is registered.

I understand use cases, where you want to end() the request separately, but in my optionion either the doOnSubscribe variant should work, or a subscribe() should trigger the end() automatically, like with Vert.x 2's mod-rxvertx.

**Comment by meshuga** [comment]
+1

**Comment by vietj** [comment]
Hi, I think it cannot be fixed, because it's the design of the HttpClient to actually perform the request when `end()` is invoked. RxJava for Vert.x 2 was hand written and could allow this behavior.

You can have the behavior you want using `Observable.create(OnSubscribe)` method like:

```
Observable<HttpClientResponse> obs = Observable.create(subscriber -> {
   HttpClientRequest req = client.request(HttpMethod.GET, 8080, "localhost", "/the_uri");
   Observable<HttpClientResponse> resp = req.toObservable();
   resp.subscribe(subscriber);
   req.end();
});
```

The `OnSubscribe ` lambda will be called when the subscription is done and not before.

**Comment by dctr** [comment]
Wouldn't it then be useful to provide a helper function like that out of the box?

**Comment by vietj** [comment]
you mean for HttpClientRequest particular case ?

**Comment by dctr** [comment]
Yes, why not. It seems like a common use case to me.

**Comment by vietj** [comment]
yes it makes sense

**Comment by alanma** [comment]
:+1: agreed for the helper function.
