### ISSUE TITLE
HttpClient with Observable causes: You must set an handler for the HttpClientResponse

### ISSUE THREAD

**Issue by tomaszmichalak** [vert-x3/vertx-rx#130]
## Description
I have a factory method:
```
  private Observable<HttpClientResponse> request(HttpClient httpClient) {
    HttpClientRequest req = httpClient.get(
      new RequestOptions()
        .setHost("localhost")
        .setPort(8080)
        .setURI("/"));
    return req
      .toObservable()
      .doOnSubscribe(subscription -> req.end());
  }
```
Then when I call it in this way:
```
      HttpClient httpClient = vertx.createHttpClient();
      Observable.fromArray(request(httpClient), request(httpClient))
        .flatMap(r -> r)
        .subscribe(next -> {
          }, Throwable::printStackTrace,
          () -> System.out.println("Observable complete"));
```
I get `java.lang.IllegalStateException: You must set an handler for the HttpClientResponse before connecting`. The same code with Flowable works as expected.

## Snippet
https://gist.github.com/tomaszmichalak/8afece6bf80bd680db2040fe57e64ee5

**Comment by vietj** [comment]
you should use the web client :-)

**Comment by vietj** [comment]
I will give it a spin tomorrow

**Comment by vietj** [comment]
Or @tsegismont is that something you can have a look at ?

**Comment by tsegismont** [comment]
@tomaszmichalak @vietj this is due to a difference in `FlowableReadStream` and `ObservableReadStream`: the latter only sets the stream handler *after* subscription.

**Comment by tsegismont** [comment]
@vietj I'm working on a fix, hopefully ready today
