### ISSUE TITLE
Potential memory leak with RxJava infinite stream 

### ISSUE THREAD

**Issue by ctranxuan** [vert-x3/vertx-rx#135]
Hi,
We might have found a possible memory leak when using a RxJava infinite stream with any Vert.x Rx Schedulers.
Basically, we create an infinite stream `Flowable` and observe the stream on one of the Vert.x schedulers.
With VisualVM, we see the memory keep growing without any garbage and reach the maximum size of memory allocated to the JVM.

We see that in an application almost in production but manage to reproduce the issue. Basically, the code looks like that:
 
```java
        Vertx vertx = Vertx.vertx();

        Scheduler scheduler = RxHelper.blockingScheduler(vertx.getDelegate()); // see rxjava-scheduler-vertx-blocking.png
//        scheduler = RxHelper.scheduler(vertx.getDelegate().createSharedWorkerExecutor("toto")); // see rxjava-scheduler-vertx-workerexecutor.png
//        scheduler = RxHelper.scheduler(vertx.getDelegate().getOrCreateContext()); // see rxjava-scheduler-vertx-eventloop.png
//        scheduler = Schedulers.io(); // see rxjava-scheduler-io.png
//        scheduler = Schedulers.computation(); // see rxjava-scheduler-computation.png

        Flowable<DataInfo> dataInfos = Flowable.interval(1, MILLISECONDS)
                                               .map(l -> new DataInfo(UUID.randomUUID().toString(), data))
                                               .share();

        int subscribersNumber = 1000;

        for (int i = 0; i < subscribersNumber; i++) {
            dataInfos.onBackpressureLatest()
                         .observeOn(scheduler)
                         .subscribe();
        }
```

You will find the code to reproduce this potential issue on the following github place: https://github.com/ctranxuan/vertx-scheduler-issue

In this project, you will find different VisualVM screenshots showing how the memory grows with different schedulers.
It seems all the Vertx schedulers are impacted. At the beginning, we thought only the blocking one was impacted but it seems the eventloop one is also impacted: the memory seems to grow slower.
The RxJava schedulers don't seem to have the problem as the screenshots show.

Environment:
 - Vert.x 3.5.0
 - Java 10 (but Java 8 also) (-Xms1024m -Xmx1024m)
 - Linux Ubuntu 16.+ / 17.04

Note: as aforementioned, we suspected the blocking scheduler the only one to be impacted because `TimedAction` are removed from the concurrentMap once the worker is disposed which can in theory never happened in case of an infinite stream. But it seems all the Vert.x schedulers are impacted.
 
We may be mistaken somewhere but don't see where.
Thanks in advance.

**Comment by vietj** [comment]
thanks we will investigate for 3.5.2

**Comment by vietj** [comment]
fixed by https://github.com/vert-x3/vertx-rx/issues/136

**Comment by vietj** [comment]
thanks for reporting, I've tried your reproducer with 3.5.2-SNAPSHOT and it allocates fine now.

**Comment by ctranxuan** [comment]
Thanks for the fix! It works like a charm!
By chance, do you have any idea when the fix will be released?
Thanks again!

**Comment by vietj** [comment]
it will be released within a couple of weeks top
