### ISSUE TITLE
Observable creation from closeable resource supplier

### ISSUE THREAD

**Issue by tsegismont** [vert-x3/vertx-rx#144]
To simplify resource management with RxJava1 and RxJava2, helper classes could provide a method to generate an `Observable` (or equivalent) from a `Single<AutoCloseable>` resource supplier). For example:

```java
  <T, R extends AutoCloseable> Flowable<T> using(Single<R> resourceSupplier, Function<R, Flowable<T>> sourceSupplier);
```

When #132 is fixed, this will be useful for any Rxified object implementing `AutoCloseable` (eg `SQLConnection`):

```java
Flowable<MyData> flowable = using(client.rxGetConnection(), conn -> {
  return conn.rxQuery(sql).flatMapPublisher(ResultSet::getResults)
    .map(MyData::fromJsonArray);
});
```

**Comment by tsegismont** [comment]
@vietj @jponge last week I made some experiments. In https://github.com/tsegismont/vertx-rx/commit/d1da5747dddf9cd297db6610049918900f221d61, you can see the code for generating a RxJava `Completable` from a `Single<R extends AutoCloseable>` resource supplier along with usage in test.

I have mixed feelings about this. On one hand, it does relieve the user from writing:

```java
resourceSupplier.flatMapCompletable(resource -> {
  Completable.using(() -> resource, r -> sourceSupplier(r), r -> disposer(r));
})
```

On the other hand:

- this code is not really Vert.x related. It's a pure RxJava helper, mirroring what's already in `Observable#using`
- if it gets merged, someone will soon ask for the same thing with `Closeable`, or any disposable object we have not yet thought about; and I guess this is why RxJava kept things at the higher level with a disposer function so that users can deal with any _resource_ (closeable, disposable, you name it).

In the end, I believe we should not try to solve again a general problem which has been solved in RxJava, and stick to a helper method for `SQLConnection` which is really what Vert.x users need:

```java
<T> Flowable<T> withConnection(SQLClient sqlClient, Function<SQLConnection, Flowable<T>> sourceSupplier);
```

Thoughts?

**Comment by jponge** [comment]
It's true that `Disposable` is here. Do you have an equivalent with your helper and just trying to fit with `Disposable`?

**Comment by jponge** [comment]
My bad

**Comment by vietj** [comment]
not yet

**Comment by tsegismont** [comment]
@jponge @vietj I went ahead and pushed this simple commit to give you a better idea of what I have in mind https://github.com/tsegismont/vertx-rx/commit/2f36211b014ecc303f9ebf4c7227fb6056d879bb

If that's fine with you, I'd do the same for all observable flavors (RxJava 1&2 + tests + docs)

**Comment by vietj** [comment]
how is this related to closable ?

**Comment by tsegismont** [comment]
@vietj see https://github.com/vert-x3/vertx-rx/issues/144#issuecomment-392701407

**Comment by tsegismont** [comment]
@vietj @jponge can you please take another look at this thread and tell me what you think? Thanks

**Comment by jponge** [comment]
What you have with https://github.com/tsegismont/vertx-rx/commit/2f36211b014ecc303f9ebf4c7227fb6056d879bb looks good to me

**Comment by tsegismont** [comment]
Closing this one in favor of #148
