### ISSUE TITLE
RxHelper does not contain method blockingScheduler(vertx, ordered)

### ISSUE THREAD

**Issue by engineerdev** [vert-x3/vertx-rx#146]
`io.vertx.rx.java.RxHelper` contains method `blockingScheduler(vertx, ordered)`, but this method not implemented in `io.vertx.rxjava.core.RxHelper`

**Comment by tsegismont** [comment]
As a workaround, you can do:

`new ContextScheduler(vertx.getDelegate().getOrCreateContext(), true, true)`

**Comment by engineerdev** [comment]
As workaround I can do: io.vertx.rx.java.RxHelper.blockingScheduler(vertx.getDelegate(), false), but I don't want.

**Comment by tsegismont** [comment]
Would you want to contribute the change?

**Comment by engineerdev** [comment]
Yes.

**Comment by engineerdev** [comment]
#147
