### ISSUE TITLE
Should generate Maybe instead of Single

### ISSUE THREAD

**Issue by Cafeinoman** [vert-x3/vertx-rx#154]
Hi,

there's a problem on code generator, when it must choose between Maybe or Single. The null-ability check don't take in count some case of AsyncResult. For example this code
```java
vertx.sharedData()
      .<String, String>rxGetAsyncMap("test")
      .flatMap(m -> m.rxGet("no.value"))
      .subscribe(System.out::println);
```
print null, which is an API violation (SingleObserver#onSuccess is call with null as parameter). Even if the case can be handle in Java by a simple null check, it throws an error in Kotlin as the parameter of subscribe here is expected to be not null.

And there's a lot of methods in this case...

**Comment by tsegismont** [comment]
This duplicates https://github.com/eclipse/vert.x/issues/2434 which has been fixed in master.

Please reopen if you find any other issue with Single/Maybe

**Comment by Cafeinoman** [comment]
Sorry, didn't see. There's the same issue with MongoClient. Think that a lot of methods outside core are in this case...

**Comment by vietj** [comment]
@Cafeinoman thing is that not all vertx maintainers are used to this Rx usability but now things are getting better, thanks to Thomas. PR to help are welcome

**Comment by tsegismont** [comment]
@Cafeinoman no problem. Do not hesitate to file issues in the relevant projects.
