### ISSUE TITLE
Buffer does not incorporate a static byte[] constructor

### ISSUE THREAD

**Issue by MikiLoz92** [vert-x3/vertx-rx#155]
The rxified version of Buffer in vertx-rx does not include the byte array constructor that its non-rx counterpart includes.

Check 
https://vertx.io/docs/apidocs/io/vertx/reactivex/core/buffer/Buffer.html
vs
https://vertx.io/docs/apidocs/io/vertx/core/buffer/Buffer.html

**Comment by vietj** [comment]
it shall be there in Vert.x 3.6, can you check the 3.6.0 SNAPSHOT ?

**Comment by vietj** [comment]
@MikiLoz92 any chance ?

**Comment by tsegismont** [comment]
It is present in 3.6.
