### ISSUE TITLE
Update RxJava2 version

### ISSUE THREAD

**Issue by rgmz** [vert-x3/vertx-rx#156]
RxJava2 [v2.2.0](https://github.com/ReactiveX/RxJava/releases/tag/v2.2.0) standardizes a number of experimental API methods (e.g. `concatMapCompleteable`) and we should at least update to that from the current version (2.1.9).

(I plan to open a PR for this soon, unless someone else wants to do it.)

**Comment by tsegismont** [comment]
@rgmz please go ahead with the PR. Thank you
