### ISSUE TITLE
Allow multiple subscribers

### ISSUE THREAD

**Issue by meshuga** [vert-x3/vertx-rx#16]
It's impossible to make more than one subscription to Observable's which are based on `SingleOnSubscribeAdapter` class, that is `ObservableFuture`, `ObservableHandler` and `ReadStreamAdapter`. If that happens, `IllegalStateException` is thrown - https://github.com/vert-x3/vertx-rx/blob/master/rx-java/src/main/java/io/vertx/rx/java/SingleOnSubscribeAdapter.java#L24

As for now I use `Observable.cache()` method as a workaround of this problem.

**Comment by vietj** [comment]
we plan to have this when we merge this branch https://github.com/vert-x3/vertx-rx/pull/7 that provides the feature to handle several subscribers.

**Comment by meshuga** [comment]
Great to hear that! :clap:
