### ISSUE TITLE
Rxified `UserSessionHandler` expects `AuthProvider`, not `OAuth2Auth`

### ISSUE THREAD

**Issue by rgmz** [vert-x3/vertx-rx#160]
`UserSessionHandler.create(authProvider)` does not work as expected with RxJava2; it will complain that it requires `AuthProvider`, not `OAuth2Auth`. [(link)](https://i.imgur.com/TrpSS6i.png)

Presumably this is because regular `OAuth2Auth` extends `AuthProviderInternal`, which extends `AuthProvider`. Whereas rxified `OAuth2Auth` does not. (?)

```java
public class HttpVerticle extends AbstractVerticle {

  @Override
  public void start(Future<Void> future) {
	// Works
	OAuth2Auth auth = GoogleAuth.create(vertx.getDelegate(), new JsonObject());
	Router router = Router.router(vertx.getDelegate());
	router.route().handler(UserSessionHandler.create(auth));

	// Doesn't work
	io.vertx.reactivex.ext.auth.oauth2.OAuth2Auth rxAuth =
		io.vertx.reactivex.ext.auth.oauth2.providers.GoogleAuth.create(vertx, new JsonObject());
	io.vertx.reactivex.ext.web.Router rxRouter = io.vertx.reactivex.ext.web.Router.router(vertx);
	rxRouter.route().handler(io.vertx.reactivex.ext.web.handler.UserSessionHandler.create(rxAuth));
  }
}
```
-------

Edit: This issue also occurs with `RedirectAuthHandler`.

**Comment by vietj** [comment]
see https://github.com/vert-x3/vertx-auth/issues/246

**Comment by vietj** [comment]
it should be ok with latest master now, can you check ?

**Comment by vietj** [comment]
```
@io.vertx.lang.reactivex.RxGen(io.vertx.ext.auth.oauth2.OAuth2Auth.class)
public class OAuth2Auth extends io.vertx.reactivex.ext.auth.AuthProvider {
  ...
}
```

**Comment by rgmz** [comment]
That looks about right.

For the record, how do you build a snapshot with the generated RX methods?

**Comment by gpthome** [comment]
Can't wait for this to be generally available.  We just side-stepped this problem today with this solution https://groups.google.com/forum/m/#!topic/vertx/6r6NwGpgScw, but I think we lost some rx functionality in the transition. 

Do you have a guess on when the next release will be available?

Thank you.

**Comment by vietj** [comment]
3.6.0 is the next thing to do in our schedule and we are not far, doing polishing.
