### ISSUE TITLE
RxHelper deployVerticle( string, ... ) missing

### ISSUE THREAD

**Issue by anewton1998** [vert-x3/vertx-rx#163]
RxHelper.deployVerticle( string, ... ) where the string is the class name of the verticle is missing.
Therefore, this method cannot be used to deploy a verticle with more than one instance as passing in an instantiated verticle is not allowed with more than one instance.

**Comment by tsegismont** [comment]
This is on purpose. If you want to do this, you can directly invoke `vertx#rxDeployVerticle(String, DeploymentOptions)`
