### ISSUE TITLE
31 Overlapping classes

### ISSUE THREAD

**Issue by jo5ef** [vert-x3/vertx-rx#168]
With vertx 3.6.0 and a dependency on `vertx-rx-java2`, we see the following warning during build:

```
[WARNING] vertx-rx-java2-gen-3.6.0.jar, vertx-rx-java2-3.6.0.jar define 31 overlapping classes: 
[WARNING]   - io.vertx.reactivex.impl.MaybeUnmarshaller
[WARNING]   - io.vertx.reactivex.MaybeHelper$1
[WARNING]   - io.vertx.reactivex.RxHelper
[WARNING]   - io.vertx.reactivex.impl.AsyncResultMaybe
[WARNING]   - io.vertx.reactivex.impl.AsyncResultSingle$1
[WARNING]   - io.vertx.reactivex.impl.FlowableReadStream
[WARNING]   - io.vertx.reactivex.impl.FlowableUnmarshaller
[WARNING]   - io.vertx.reactivex.impl.AsyncResultCompletable
[WARNING]   - io.vertx.reactivex.ObservableHelper
[WARNING]   - io.vertx.reactivex.SingleHelper$1
[WARNING]   - 21 more...
```

Is this intended?

**Comment by vietj** [comment]
you can that classes are duplicates in these two jars ?

it's not I think

**Comment by jo5ef** [comment]
Yes, these classes are both in `vertx-rx-java2-get-3.6.0.jar` and in `vertx-rx-java2-3.6.0.jar`, hence the warning. I haven't looked into why.

**Comment by vietj** [comment]
according to @cescoffier this is a normal situation @jo5ef

**Comment by vietj** [comment]
this is due to the BnD plugin (for the record) that copies these classes in this jar

**Comment by cristiammercado** [comment]
My temporary solution for this is:

```
    <dependency>
        <groupId>io.vertx</groupId>
        <artifactId>vertx-rx-java</artifactId>
        <version>3.6.0</version>
        <exclusions>
            <exclusion>
                <groupId>io.vertx</groupId>
                <artifactId>vertx-rx-java-gen</artifactId>
            </exclusion>
        </exclusions>
    </dependency>

    <dependency>
        <groupId>io.reactivex</groupId>
        <artifactId>rxjava</artifactId>
        <version>1.3.8</version>
    </dependency>
```

**Comment by vietj** [comment]
does not happen in vertx master (4.0)

**Comment by vietj** [comment]
happens in 3.9

**Comment by tsegismont** [comment]
This one is outdated. Try creating this project with the starter:

`curl -G https://start.vertx.io/starter.zip -d "groupId=com.example" -d "artifactId=starter" -d "vertxVersion=3.9.4" -d "vertxDependencies=vertx-rx-java2" -d "language=java" -d "jdkVersion=11" -d "buildTool=maven" --output starter.zip`

Then `mvn clean package`.

There are no duplication warnings.

The two dependencies brought are `vertx-rx-gen-3.9.4.jar` and `vertx-rx-gen-3.9.4.jar` and if you inspect them there is no package overlap.
