### ISSUE TITLE
Missing call to this.fireComplete() in ObservableHandler

### ISSUE THREAD

**Issue by bissaias** [vert-x3/vertx-rx#17]
In the `ObservableHandler<T>` class you have 
```
...
 public ObservableHandler() {
    this(new HandlerAdapter<T>() {
      @Override
      protected void dispatch(T event) {
        this.fireNext(event);
        //this.fireComplete() should be called here
      }
    });
  }
...
```
I think the `dispatch(T event)` implementation should call also `this.fireComplete()` as per the commented line above,  similarly to the `ObservableFuture` class. Otherwise the Observer's state is not updated.

**Comment by vietj** [comment]
the problem with adapter is that you don't know how many times an Handler will be invoked, it could be one or more (like periodic timers or event subscribers). So we can only invoke fireNext() on dispatch and not fireComplete.

**Comment by vietj** [comment]
actually this should be flexible and declared when creating the ObservableHandler

**Comment by vietj** [comment]
and it should complete by default (which is the behavior you want)
