### ISSUE TITLE
Unnamed module reads package io.vertx.reactivex from both vertx.rx.java2 and vertx.rx.java2.gen

### ISSUE THREAD

**Issue by Falx** [vert-x3/vertx-rx#173]
Making a basic project with vertx 3.6.0 where rxjava2 is used, I get the next errors:
Error:java: the unnamed module reads package io.vertx.reactivex from both vertx.rx.java2 and vertx.rx.java2.gen

Is there still a split package then? This blocks modularization of our vertx based applications.

**Comment by cescoffier** [comment]
I believe it's related to https://github.com/vert-x3/vertx-rx/issues/172.

**Comment by timofeevda** [comment]
Ahhh, my bad. When I was fixing #172 I forgot to push changes which add explicit dependency on vertx-rx-gen in rxjava and rxjava2 modules. So now you also need to add it to project dependencies list explicitly. To fix this inconvenience we need to make vertx-rx-gen dependency explicit in rx-java-gen and rx-java-gen2. Then everything will work like it worked before without manual edits in dependency lists

**Comment by vietj** [comment]
can you make a new PR ?

I believe this won't be released before 3.6.2 however.

Julien

**Comment by vietj** [comment]
to clarify can you tell which use case works and don't work without this dependency ?
