### ISSUE TITLE
Breaking change in 4.0

### ISSUE THREAD

**Issue by jponge** [vert-x3/vertx-rx#177]
Existing projects that used code generation of reactive APIs from _asynchronous_ interfaces like steps 8 to 10 in the guide for Java developers face compilation failures when upgrading to 4.0.0-SNAPSHOT.

The following new dependency needs to be added:

```xml
<dependency>
  <groupId>io.vertx</groupId>
  <artifactId>vertx-rx-java2-gen</artifactId>
  <version>${vertx.version}</version>
</dependency>
```

Also, the version needs to be added since the module is not in `vertx-stack-depchain`.

**Comment by vietj** [comment]
I think so far we haven't properly documented how codegen works for non vertx project (as it was rather used only in stack initially). I'm thinking that the vertx advanced guide should contain a section about code generating asynchronous APIs with vertx.

**Comment by mahinshaw** [comment]
I am having issues where vertx is no longer creating rx service proxies after 3.6.0. Is this related to this issue?

More spefically, using 3.6.2 for all vertx packages will not yield and rx-ified service proxy. However, if is switch the annotationProcessor (in gradle) to use version 3.6.0 for vertx-rx-java2 and leave all other artifacts as 3.6.2 the codegen outputs an rx-ified service proxy.

**Comment by vietj** [comment]
you need also to use the proper dependencies, I will update the vertx examples to have an rx-ified version I think

**Comment by vietj** [comment]
@mahinshaw you can look at the example https://github.com/vert-x3/vertx-examples/tree/master/rxjava-2-examples

**Comment by mahinshaw** [comment]
@vietj thanks. I will give that a go later today and get back to you

**Comment by mahinshaw** [comment]
@vietj Adding `vertx-rx-java2-gen` as an `annotationProcessor` for gradle solved the issue. Thanks. It might be worth adding a gradle build for all of this as well. My issue is probably more relavent to the new annotation processor flow in gradle 4/5. Maybe I can get some time to work on a PR for the aforementioned example and add a `build.gradle`.

**Comment by vietj** [comment]
@mahinshaw sure thing thanks

**Comment by jponge** [comment]
Closing, the new module names have been stable for some time
