### ISSUE TITLE
rxFindOne() in mongoDb module returns null json in case there is no match

### ISSUE THREAD

**Issue by amit-bhandari** [vert-x3/vertx-rx#183]
I am trying to find one document in rxEntension of mongo db module.

`mongoClient
.rxFindOne(collection, JsonObject().put("email", updateJson.getString("email")), null)
                .flatMap { billerJson -> }`

In case there is no result, instead of returning empty json, billerJson comes to be null but as it is of non-nullable type, it given null pointer crash in Kotlin.

Is there work around this issue?

**Comment by vietj** [comment]
I think that `findOne` methods should be declared like:

```
  MongoClient findOne(String collection, JsonObject query, @Nullable JsonObject fields, Handler<AsyncResult<@Nullable JsonObject>> resultHandler);
```

so the generated type is `Maybe<JsonObject` and not `Single<JsonObject>`

**Comment by amit-bhandari** [comment]
Is it already corrected? I checked the source and it shows the result as nullable in mongo client.

**Comment by vietj** [comment]
yes it seems corrected.

```
  MongoClient findOne(String collection, JsonObject query, @Nullable JsonObject fields, Handler<AsyncResult<@Nullable JsonObject>> resultHandler);
```

in 3.7 branch

**Comment by vietj** [comment]
the corresponding RxJava code:

```
  /**
   * Find a single matching document in the specified collection
   * <p>
   * This operation might change <i>_id</i> field of <i>query</i> parameter
   * @param collection the collection
   * @param query the query used to match the document
   * @param fields the fields
   * @return 
   */
  public Maybe<JsonObject> rxFindOne(String collection, JsonObject query, JsonObject fields) { 
    return io.vertx.reactivex.impl.AsyncResultMaybe.toMaybe(handler -> {
      findOne(collection, query, fields, handler);
    });
  }
```

**Comment by tsegismont** [comment]
The breaking changes page in 3.7 must be updated, if it hasn't already :)

**Comment by vietj** [comment]
I don't know when this was actually fixed

**Comment by vietj** [comment]
looks like it is https://github.com/vert-x3/vertx-mongo-client/pull/166

**Comment by vietj** [comment]
I'll update the wiki page

**Comment by vietj** [comment]
done

**Comment by amit-bhandari** [comment]
Thanks !
