### ISSUE TITLE
RxJava 2 : errors do not always propagate to WriteStreamSubscribers

### ISSUE THREAD

**Issue by dave-fl** [vert-x3/vertx-rx#188]
I am noticing that  in the following example order matters for the WriteStreamSubscriber and I am not sure why.

[Example here](https://github.com/dave-fl/writestream-issue/blob/master/src/main/java/com/example/verticles/WriteStreamSubscriberProxyVerticle.java)

Basically if the target destination URL is correct, this will run just fine.  Even if you move the subscription at line 69 to line 75 it will also work fine.

If you intentionally introduce an error e.g. an invalid target URL then errors do not propagate correct.  In the current state they will, but if you move line 69 to 75 they will not.  Does not matter if you use pause/resume etc...

Is this to be expected?  I wasn't sure why the handler that is being defined is not being used instead of the RxjavaPlugin that is trying to be called.

```
io.reactivex.exceptions.UndeliverableException: The exception could not be delivered to the consumer because it has already canceled/disposed the flow or the exception has nowhere to go to begin with. Further reading: https://github.com/ReactiveX/RxJava/wiki/What's-different-in-2.0#error-handling | java.net.UnknownHostException: failed to resolve 'badhost'. Exceeded max queries per resolve 4 
	at io.reactivex.plugins.RxJavaPlugins.onError(RxJavaPlugins.java:367)
	at io.vertx.reactivex.impl.WriteStreamSubscriberImpl.lambda$onSubscribe$0(WriteStreamSubscriberImpl.java:67)
	at io.vertx.core.http.impl.HttpClientRequestBase.handleException(HttpClientRequestBase.java:139)
	at io.vertx.core.http.impl.HttpClientRequestImpl.lambda$null$8(HttpClientRequestImpl.java:505)
```

**Comment by laurentvaills** [comment]
That issue seems similar to this one I just opened, with a simpler reproducer IMO: #242 

I also added the results of my investigation.
