### ISSUE TITLE
Flowable returned by HttpServerRequest.toFlowable() does not emit events for requests with empty body

### ISSUE THREAD

**Issue by myhau** [vert-x3/vertx-rx#191]
## How to reproduce:

1. `git clone https://github.com/myhau/vertx-hangs-with-empty-body-reproduce`
2. `cd vertx-hangs-with-empty-body-reproduce`
3. run vertx server by executing main
4. `curl -X POST -d 'some data' localhost:8080` - requests has body - this works
5. `curl -X POST localhost:8080` - request has empty body - this fails

**Comment by vietj** [comment]
thanks

**Comment by vietj** [comment]
See the bug https://github.com/eclipse-vertx/vert.x/issues/2904 that was fixed for 3.7.1 that fixes this issue. Thanks for the reproducer it helped quickly resolve the issue.
