### ISSUE TITLE
Generated RxJava method EventBus.registerDefaultCodec missing

### ISSUE THREAD

**Issue by AlexBischof** [vert-x3/vertx-rx#192]
Is there any particular reason why EventBus.registerCodec is generated but EventBus.registerDefaultCodec() is not?

I know it is possible with the following snippet but it looks a little bit ugly.

```
eventBus.getDelegate().registerDefaultCodec(MyEntity.class, new MyEntityCodec());
```
Kind regards
Alex

**Comment by tsegismont** [comment]
It's not possible because `Class` is not a supported by vertx-codegen

**Comment by AlexBischof** [comment]
Thank you, i've missed that.

**Comment by tsegismont** [comment]
You're welcome.
