### ISSUE TITLE
io.vertx.reactivex.ext.web.handler.CorsHandler is missing allowedMethods

### ISSUE THREAD

**Issue by mbykovskyy** [vert-x3/vertx-rx#193]
The reactive version of `CorsHandler` is missing an `allowedMethods` method, which I found quite convenient in the regular `io.vertx.ext.web.handler.CorsHandler`.

**Comment by tsegismont** [comment]
@mbykovskyy thanks for reporting! Most probably, codegen allowed sets of enums after this method was added, and since there's a workaround, nobody complained so far.

It will be fixed in the next micro release.
