### ISSUE TITLE
Add support for Handler<@Options> and Handler<AsyncResult<@Options>>

### ISSUE THREAD

**Issue by Narigo** [vert-x3/vertx-rx#2]
As mentioned by Julien on the mailing list, we need to add support for these two new possible use cases just like JavaScript and Groovy.

**Comment by vietj** [comment]
I think someone asked about this recently in a list.

**Comment by vietj** [comment]
implemented last week actually by https://github.com/vert-x3/vertx-rx/commit/abce7ac0157a44a624a986d5a4c348b0cfbdd85d
