### ISSUE TITLE
ReadStreamSubscriber does not properly handle errors delivered during subscribe

### ISSUE THREAD

**Issue by sfitts** [vert-x3/vertx-rx#200]
Version -- 3.7.1

There are several Rx chains which will trigger a call to `onError` on the downstream immediately during subscription.  When this happens with an instance of `ReadStreamSubscriber` there is no way to actually receive the error since any attempt to set the exception or end handlers results in an `IllegalStateException` (even if the stream is paused).

Consider the following JUnit test:

```
    @Test
    public void errorToReadStream() throws InterruptedException {
        Flowable<Object> errorFlowable = Flowable.error(new RuntimeException("This is my error"));
        ReadStream<Object> errorStream = ReadStreamSubscriber.asReadStream(errorFlowable, 
                java.util.function.Function.identity());
        CountDownLatch latch = new CountDownLatch(1);
        List<Throwable> errors = new ArrayList<>();
        errorStream.pause();
        errorStream.handler(obj -> {});
        errorStream.exceptionHandler(errors::add);
        errorStream.endHandler(aVoid -> {
            latch.countDown();
        });
        errorStream.resume();
        latch.await();
        Assert.assertFalse(errors.isEmpty());
    }
```

Currently this will fail when setting the exception handler.  Ideally it would be nice if on the resume the exception and then end handler's were called (to deliver the error).

**Comment by vietj** [comment]
the end and exception handlers should always be set before the item handler which will trigger the subscription. the current code does not take in account that pause/resume are called.

**Comment by sfitts** [comment]
Unfortunately there is absolutely no way to do this since the stream has already subscribed and received the error *before* it returns from `asReadStream` (so the placement of the call to `handler` is irrelevant).  Basically the stream returned is completely unusable and there is no way to actually process the error that the Rx chain produces.

The following code produces the same error:

```
    @Test
    public void errorToReadStream() throws InterruptedException {
        Flowable<Object> errorFlowable = Flowable.error(new RuntimeException("This is my error"));
        ReadStream<Object> errorStream = ReadStreamSubscriber.asReadStream(errorFlowable, 
                java.util.function.Function.identity());
        CountDownLatch latch = new CountDownLatch(1);
        List<Throwable> errors = new ArrayList<>();
        errorStream.pause();
        errorStream.exceptionHandler(errors::add);
        errorStream.endHandler(aVoid -> {
            latch.countDown();
        });
        errorStream.handler(obj -> {});
        errorStream.resume();
        latch.await();
        Assert.assertFalse(errors.isEmpty());
    }
```

In fact all you need to get the exception is..

```
        Flowable<Object> errorFlowable = Flowable.error(new RuntimeException("This is my error"));
        ReadStream<Object> errorStream = ReadStreamSubscriber.asReadStream(errorFlowable, 
                java.util.function.Function.identity());
        errorStream.exceptionHandler(ex -> {});
```

**Comment by sfitts** [comment]
Any update on this?  I created a patched version which we are using in its place, but an official fix would be preferable.
