### ISSUE TITLE
RxJava 3

### ISSUE THREAD

**Issue by daihy8759** [vert-x3/vertx-rx#204]
![image](https://user-images.githubusercontent.com/6057326/60810872-978e7800-a1c0-11e9-917b-7539a5bde674.png)

**Comment by vietj** [comment]
we will investigate this soon and likely provide support for 3, thanks for reporting this.

**Comment by cvgaviao** [comment]
FYI, https://github.com/ReactiveX/RxJava/wiki/What's-different-in-3.0

**Comment by vietj** [comment]
It seems to me that Rx 3.0 is a bit a joke and it does not bring enough stuff on the table, I see it more as a glorified 2.3.0 than a real 3.0 .

A real 3.0 would have embraced Java 8+ at least.

**Comment by cvgaviao** [comment]
> A real 3.0 would have embraced Java 8+ at least.

I agree with you. It seems to me that it is because rxJava is heavily used by Android guys that are stuck in java6 :(

**Comment by vietj** [comment]
according to the issue in their tracker, people said that Android should not be an issue anymore and they would be fine actually continuing using 2.x

**Comment by vietj** [comment]
event Java 11 would be nice actually with Flow API

**Comment by aaloise** [comment]
I think the decision to release version 3 instead of 2.3 for example is related to many API changes. What leads me to interpret this are the sentences that states RxJava 2 API mistakes being fixed and also it's limitations.

Anyway, I believe that Vert.x will adopt RxJava 3 in due course.

**Comment by vietj** [comment]
@aaloise yes, ignore the rant where I was just bitching at RxJava 2 due to my disappointment by the lack of ambition

**Comment by vietj** [comment]
In another discussion some argue for using a more recent version of Java:

- https://github.com/ReactiveX/RxJava/issues/5622#issuecomment-465245436
- https://github.com/ReactiveX/RxJava/issues/5622#issuecomment-467127959

**Comment by aaloise** [comment]
Good news! Since version 3.0.0-RC7, RxJava is moved do a Java 8 baseline.

https://github.com/ReactiveX/RxJava/issues/6803

**Comment by vietj** [comment]
that's a great news @aaloise :-)

**Comment by vietj** [comment]
however it seems still to use its RX2 interfaces, e.g https://github.com/ReactiveX/RxJava/blob/3.x/src/main/java/io/reactivex/rxjava3/functions/Consumer.java instead of Java 8 Consumer interface

**Comment by aaloise** [comment]
Let's see how things go, it's still in RC stage. I am not 100% sure, but I think that it has something to do with Android desugar...

"For Android development, the latest Android Studio is always recommended which is already able to desugar many Java 8 constructs. The upcoming AS 4 will support even more desugaring for older API levels. Until then, one should stick to the non-Java 8 standard methods so the Java 8 methods can be ignored by AS."

**Comment by vietj** [comment]
wait and see indeed :-)

**Comment by aaloise** [comment]
@vietj David Karnok explained to me why RxJava 3 still uses it's own interfaces instead the ones of Java 8:

"Java functional interfaces can't throw checked exceptions but ours can. If we switched over, a protocol would be needed to sneak out checked exceptions. This adds complications to both our users (try-catch in many lambdas) and library internals (proper unwrapping in a ton of operators). Reactor did it and suffered from related issues for months. Besides, functional interfaces and lambdas can be freely defined. Since the business logic is customized through it every time, I don't think there exist a repository of java functionals so no direct interop is likely needed. Otherwise, use lambda::apply to convert them at your will."

**Comment by vietj** [comment]
@aaloise interesting thanks

**Comment by vietj** [comment]
For this generator we should skip the generation of Handler and Future methods and provide only Rx3 types I think, at least we should skip Handler

**Comment by angelsanz** [comment]
Is RxJava 3 support planned for Vert.x 4 or postponed to a later Vert.x release?

**Comment by vietj** [comment]
it is not yet clear, if that's not in Vert.x 4.0 then it would be in 4.1

**Comment by vietj** [comment]
instead proper issue https://github.com/vert-x3/vertx-rx/issues/204

**Comment by cvgaviao** [comment]
> instead proper issue #204

You have linked this same closed issue

**Comment by vietj** [comment]
here is the correct one https://github.com/vert-x3/vertx-rx/issues/240
