### ISSUE TITLE
Exceptions within a subscriber stops a consumer

### ISSUE THREAD

**Issue by johnoliver** [vert-x3/vertx-rx#21]
Following code demonstrates the problem. As can be seen if the subscriber throws an error the consumer is killed. This was unexpected for me as I expected consumers to remain subscribed even though a single invocation may throw an exception.

```
        new EventBus(eventBus)
                .consumer("foo")
                .toObservable()
                .subscribe(msg -> {
                    System.out.println("Seen: " + msg.body());
                    if (msg.body().equals(2)) {
                        throw new RuntimeException("error");
                    }
                });

        eventBus.send("foo", 1);
        eventBus.send("foo", 2);
        eventBus.send("foo", 3);
```

**Comment by vietj** [comment]
I think the consumer is still subscribed to the event bus but the lambda subscribed to the Observable<Message> is unsubscribed and you should be able to resubscribe to the Observable<Message> .

**Comment by mozinrat** [comment]
If it works can you post the solution. Got same issue while using lambda expression.

**Comment by johnoliver** [comment]
This doesn’t really work since the only way to know that an error has occurred is to surround the subscribe block with a try catch block (note onError does not apply to errors in subscribers), and if you are doing that rather than resubscribing you may as well just not rethrow the exception. So as far as I can tell the only way to deal with this at the moment is to surround every subscriber to a .consumer with a try catch block, and if you forget it will become unreliable.

You will also need to catch exceptions on any function chained off of a consumer too, otherwise you would need to use onError to try to do the resubscription as mentioned.

I am willing to bet other methods that are expected to be permanent such as periodic also suffer from this problem.

**Comment by subicura** [comment]
+1

**Comment by tsegismont** [comment]
Closing invalid: this is the standard behavior in RxJava. When the subscriber throws an exception, it is reported to the `onError` channel and this terminates the subscription.
