### ISSUE TITLE
vertx reactivex kafka client doesn't support subscribe on Pattern

### ISSUE THREAD

**Issue by anthonyshull** [vert-x3/vertx-rx#215]
The vertx kafka client allows consumer subscriptions on regex patterns, but the reactivex implementation does not. Is there a reason for this? I'm willing to contribute a pull request if it is possible.

**Comment by vietj** [comment]
can you point out which method shall be used on the kafka side ?

**Comment by anthonyshull** [comment]
io.vertx.reactivex.kafka.client.consumer.KafkaConsumer.subscribe() is the method missing the Pattern signature that exists in io.vertx.kafka.client.consumer.KafkaConsumer. It looks like there is a @GenIgnore above the method def. Is there a reason? The docs give an example using a Pattern: https://vertx.io/docs/vertx-kafka-client/java.

**Comment by anthonyshull** [comment]
The underlying org.apache.kafka.clients.consumer.KafkaConsumer has subscribe(java.util.regex.Pattern pattern) method.

**Comment by vietj** [comment]
I think that we could expose such feature and annotate the method to tolerate the Pattern type, can you have a look at contributing this ?

**Comment by anthonyshull** [comment]
Yeah, I'll take a look at it this week.

**Comment by anthonyshull** [comment]
I am going to close this here and open in vertx-kafka-client.
