### ISSUE TITLE
AsyncFile#toSubscriber#onComplete is triggered before the actual write

### ISSUE THREAD

**Issue by Sammers21** [vert-x3/vertx-rx#218]
### Version

3.8.5

### Context

I figured out that `AsyncFile#toSubscriber#onComplete` action might be triggered before the actual write. 

### Do you have a reproducer?

Yes. The reproducer is located here: https://github.com/Sammers21/vertx-fs-reproducer 

### Steps to reproduce

Just run the `gradle test` command. The test fail has been reproduced in a Github action run: https://github.com/Sammers21/vertx-fs-reproducer/runs/425809354#step:5:33

### Extra

* JVM - OpenJDK 11.0.5
* OS - Mac OS 10.15.3

**Comment by tsegismont** [comment]
This happens because in previous Vert.x version we didn't have the `io.vertx.core.streams.WriteStream#end(io.vertx.core.Handler<io.vertx.core.AsyncResult<java.lang.Void>>)` method.

We could use this now to make sure there aren't any more outstanding writes and file is actually closed.
