### ISSUE TITLE
PgConnection wrapped by rx.SqlConnection instead of rx.PgConnection

### ISSUE THREAD

**Issue by bhowell2** [vert-x3/vertx-rx#243]
Been away from vert.x for a while and took me a minute to gather my bearings and remember I've run into this issue before (other rxified apis). 

Non-rxified:
```java
// left out generics below

abstract class PoolBase extends SqlClientBase implements Pool {

  // PgPoolImpl will implement this, returning PgConnectionImpl (no problem non-rxified)
  protected abstract SqlConnectionImpl wrap(ContextInternal context, Connection conn);

  // relevant
   @Override
  public Future<SqlConnection> getConnection() {
    ContextInternal current = vertx.getOrCreateContext();
    Object metric;
    if (metrics != null) {
      metric = metrics.enqueueRequest();
    } else {
      metric = null;
    }
    Promise<Connection> promise = current.promise();
    acquire(promise);
    if (metrics != null) {
      promise.future().onComplete(ar -> {
        metrics.dequeueRequest(metric);
      });
    }
    return promise.future().map(conn -> {
      SqlConnectionImpl wrapper = wrap(current, conn);
      conn.init(wrapper);
      return wrapper;
    });
  }

}


class PgPoolImpl extends PoolBase implements PgPool {
  // wrap is called by getConnection of PoolBase and gives you the PgConnection
   @Override
  protected SqlConnectionImpl wrap(ContextInternal context, Connection conn) {
    return new PgConnectionImpl(factory, context, conn, tracer, metrics);
  }
}

```

RxVersion:
```java

@RxGen(io.vertx.sqlclient.Pool.class)
public class Pool extends io.vertx.reactivex.sqlclient.SqlClient {
  // this is where the error is. 
  // PgPool below extends this class and passes PgPool as the delegate 
  // delegate.getConnection() is called and returns PgConnectionImpl
  // So far so good.
  // HOWEVER, this is where it breaks down. now the returned PgConnectionImpl 
  // is wrapped with the rxified SqlConnection rather than the rxified PgConnection
  /**
   * Get a connection from the pool.
   * @param handler the handler that will get the connection result
   */
  public void getConnection(Handler<AsyncResult<io.vertx.reactivex.sqlclient.SqlConnection>> handler) { 
    delegate.getConnection(new Handler<AsyncResult<io.vertx.sqlclient.SqlConnection>>() {
      public void handle(AsyncResult<io.vertx.sqlclient.SqlConnection> ar) {
        if (ar.succeeded()) {
          handler.handle(io.vertx.core.Future.succeededFuture(io.vertx.reactivex.sqlclient.SqlConnection.newInstance((io.vertx.sqlclient.SqlConnection)ar.result())));
        } else {
          handler.handle(io.vertx.core.Future.failedFuture(ar.cause()));
        }
      }
    });
  }
}

@RxGen(io.vertx.pgclient.PgPool.class)
public class PgPool extends io.vertx.reactivex.sqlclient.Pool {
  
  private final io.vertx.pgclient.PgPool delegate;
  
  public PgPool(io.vertx.pgclient.PgPool delegate) {
    super(delegate);
    this.delegate = delegate;
  }

}

```

To get around this issue, you call:
```java
  // rxified
io.vertx.reactivex.pgclient.PgPool.rxGetConnection(conn -> 
  io.vertx.reactivex.pgclient.PgPool.rxGetConnection.newInstance(
    (io.vertx.pgclient.PgConnection)conn.getDelegate()
  )
)
  // non-rxified version:
io.vertx.reactivex.pgclient.PgPool.rxGetConnection(conn -> 
  (io.vertx.pgclient.PgConnection)conn.getDelegate()
)
```

Now that i'm walking through this issue completely, I remember running into other issues like this throughout the codebase with the rxified API.

E.g.,
```java
  // note you have to call getDelegate here to call _compute_ as it is not exposed on the rxified localmap
io.vertx.reactivex.core.Vertx.sharedData().getLocalMap("whatever").getDelegate().compute()
  // of course can call it this way:
io.vertx.reactivex.core.Vertx..getDelegate().sharedData().getLocalMap("whatever").compute()
```

In the end maybe this is just a minor inconvenience. I had been so long away from vertx (and java) it wasnt immediately clear to me how to get the PgConnection I was looking for with the rxified api. Whoever works on the codegen will know better than me, but I don't imagine it's going to be an easy fix.

Created a reproducer here: https://github.com/bhowell2/VertxUnnamedModuleSqlClientReproducer

**Comment by vietj** [comment]
thanks @bhowell2 that one might be tough to work around for us

**Comment by vietj** [comment]
perhaps one way would be to use an adapter pattern, i.e on `SqlConnection` have a cast:

```java
<C extends SqlConnection> C as(Class<C> type);
```

that can be then used to do: `connection.as(PgConnection.class)` that would perform the cast and rewrap the connection with the right wrapper.

I'm not 100% sure we can do better here.

**Comment by vietj** [comment]
cc @tsegismont

**Comment by tsegismont** [comment]
I can see three options:

1. support bounded type parameters in codegen, then
   - change `Pool` to `Pool<C extends SqlConnection>`
   - change `PgPool to `Pool<SqlConnection>
2. rework the API
   - change `Pool` to `Pool<C>`
   - move default methods (`withConnection`, `withTransaction`) from `PgPool` to subclasses
3. hack `rx-gen`
   - make a special implementation of `PgPool.rxGetConnection` that wraps the delegate with rxified PgConnection

I'm not sure how much effort is needed for option 1. Option 2 is most probably not possible before a new major version.
Option 3 well... is ugly but can make everyone happy.

I'm not sure how you would implement the `<C extends SqlConnection> C as(Class<C> type);`.
Perhaps with a `rx-gen` hack too?

**Comment by vietj** [comment]
Using a class as parameter is supported already using reflection with https://github.com/vert-x3/vertx-rx/blob/0948a3fff166ff5db4d2e7c0776cbe98ab55db67/rx-gen/src/main/java/io/vertx/lang/rx/TypeArg.java#L14

How are 1/2 different ? it is not clear.

1. seems like a breaking change because users would have to change `Pool` occurences to `Pool<SqlConnection>` in their code. Also it requires codegen to support type variable bounds.

**Comment by vietj** [comment]
3. is actually recognized as a pattern (which does not make it more sexy btw) https://www.programcreek.com/2011/09/adapters-in-eclipse/ - just saying

**Comment by tsegismont** [comment]
I think my comment answers all your questions. Is there any particular point that is not clear>

**Comment by tsegismont** [comment]
> is actually recognized as a pattern (which does not make it more sexy btw) https://www.programcreek.com/2011/09/adapters-in-eclipse/ - just saying

Are you talking about what I described as option 3 or the `as()` method?

**Comment by vietj** [comment]
> > is actually recognized as a pattern (which does not make it more sexy btw) https://www.programcreek.com/2011/09/adapters-in-eclipse/ - just saying
> 
> Are you talking about what I described as option 3 or the `as()` method?

yes

**Comment by vietj** [comment]
> I think my comment answers all your questions. Is there any particular point that is not clear?

I can read for 1. : "change PgPool to Pool" and I think it should read "change PgPool to Pool<PgConnection>" but I'm not sure of that, that's why I asked

**Comment by tsegismont** [comment]
ok, thanks

**Comment by vietj** [comment]
I think one thing we can do is provide a static method for each subclass:

```java
PgConnection conn = PgConnection.wrap(conn);
````

It is similar to as but done differently and it is better like this as it does not appear on the `SqlConnection` interface.

**Comment by tsegismont** [comment]
Nice idea

**Comment by tsegismont** [comment]
@vietj I will prepare a PR for this
