### ISSUE TITLE
Add generation of rx-ified version of Web OpenApi

### ISSUE THREAD

**Issue by JonasTaulienSolutions** [vert-x3/vertx-rx#248]
([I asked a question in the google group](https://groups.google.com/g/vertx/c/kBGLXHLKrQg) and received an answer from @vietj that I should create an issue here.)

#### Describe the feature
Please add the generation of the RxJava2 Version of the Web OpenApi module.
I would suggest `vertx-web-openapi-rx-java2` as artifact id.
I also want to suggest to document this new package in [the Web OpenApi-Documentation](https://vertx.io/docs/vertx-web-openapi/java/).

#### Use cases
To integrate the Web OpenApi-Module with a Project that havily uses Vert.x RxJava 2.

#### Contribution
It would be great if someone else would do this. But if you think, that this would be a great fit for a first contribution to the Vert.x-project and there exists documentation on how to do this, I would be willing to help :)

**Comment by vietj** [comment]
see https://github.com/vert-x3/vertx-rx/commit/361ea84fc3a59a7df334f3e68a169eaf1732282d
