### ISSUE TITLE
Rxified Redis and Cookie session stores are missing

### ISSUE THREAD

**Issue by tsegismont** [vert-x3/vertx-rx#249]
As a workaround, users must create a bare `SessionHandler` with Redis/Cookie store and then wrap the instance with rxified `SessionHandler`.

**Comment by kalaibabu** [comment]
Hi ,

I have referred to the vertx-rx-java-3.8.0.jar method below
imports  io.vertx.rxjava.redis
setBinaryWithOptions - vert.x.3

Vert.x.4 , vertx-rx-java-4.1.2.jar contains what will be considered equivalent methods
