### ISSUE TITLE
Add generation of rx-ified version of Web OpenApi

### ISSUE THREAD

**Issue by jekkel** [vert-x3/vertx-rx#256]
#### Describe the feature

Please add the generation of the RxJava Version of the Web OpenApi module.
I would suggest `vertx-web-openapi-rx-java` as artifact id.
I also want to suggest to document this new package in [the Web OpenApi-Documentation](https://vertx.io/docs/vertx-web-openapi/java/).
#### Use cases

To integrate the Web OpenApi-Module with a Project that havily uses Vert.x RxJava.

Similar to #248 but for RxJava 1.

**Comment by vietj** [comment]
we still provide RxJava 1 support, but we don't generate code for new vertx module as RxJava 1 is not really supported anymore on the community side of ReactiveX

**Comment by vietj** [comment]
you should switch to RxJava2 or RxJava3 if you are using Vert.x 4

**Comment by jekkel** [comment]
I was afraid this would happen. Although understandable for us it makes a significant changeset (upgrade to vert.x 4) even bigger since it has to include upgrade to Rx > 1 as well.

Thanks for clarification though.
