### ISSUE TITLE
RxJava3 WriteStream interface does not include #toSubscriber() method

### ISSUE THREAD

**Issue by pgalbraith** [vert-x3/vertx-rx#306]
### Version

4.5.7

### Do you have a reproducer?

https://vertx.io/docs/apidocs/io/vertx/rxjava3/core/streams/WriteStream.html

### Extra

It looks like [ReadStream](https://vertx.io/docs/apidocs/io/vertx/rxjava3/core/streams/ReadStream.html) is getting the [#toFlowable()](https://vertx.io/docs/apidocs/io/vertx/rxjava3/core/streams/ReadStream.html#toFlowable--) and [#toObservable()]([toObservable](https://vertx.io/docs/apidocs/io/vertx/rxjava3/core/streams/ReadStream.html#toObservable--)()) methods defined, but [WriteStream](https://vertx.io/docs/apidocs/io/vertx/rxjava3/core/streams/WriteStream.html) seems to be missing #toSubscriber() and #toObvserver()

**Comment by tsegismont** [comment]
Fixed in b7442538
