### ISSUE TITLE
Missing method deployVerticle(Verticle verticle)

### ISSUE THREAD

**Issue by paulbakker** [vert-x3/vertx-rx#32]
The `Vertx.deployVerticle(Verticle verticle)` methods are missing on the Rx API, only the String versions are available.

**Comment by cescoffier** [comment]
This method is annotated with `@GenIGnore` in vert.x core, so it is not "generated".

You can access it using `getDelegate()`. Something like:

```
((io.vertx.core.Vertx) vertx.getDelegate()).deployVerticle(myVerticleInstance)
```

**Comment by paulbakker** [comment]
Because it is only available for Java, not for JS and such? Makes sense from a technical perspective at least. I'm fine with closing this as "wont't fix".

**Comment by cescoffier** [comment]
Yes, it's for this reason. It's limited to java. Right now, codegen is not able to select the method to generate based on the target platform / language. So as soon as we add @GenIgnore, it won't be generated. Should be add something in the RXHelper ? I would let @vietj chooses.

**Comment by vietj** [comment]
I think RxHelper is a good intermediate solution. The RxHelper would unwrap the Vertx and deploy it using the real vertx anyway.
