### ISSUE TITLE
Generated Credentials interface has no implementations

### ISSUE THREAD

**Issue by jjasper714** [vert-x3/vertx-rx#321]
### Version

5.0.0CR2 

### Context

I was attempting to upgrade to 5.0.0CR2 when I ran into a problem using the generated rxjava3 OAuth2Auth class. The `oAuth2Auth#rxAuthenticate` method requires a generated rxjava3 `Credentials` class. However, there are no generated implementations of Credentials. In previous versions, `oAuth2Auth#rxAuthenticate` appears to have accepted the non-generated version of Credentials, so it's not clear to me if Credentials should even have a generated type.

### Do you have a reproducer?

```java
import io.vertx.rxjava3.core.Vertx;
import io.vertx.rxjava3.ext.auth.oauth2.OAuth2Auth;
import io.vertx.ext.auth.oauth2.OAuth2FlowType;
import io.vertx.ext.auth.oauth2.OAuth2Options;
import io.vertx.ext.auth.oauth2.Oauth2Credentials;

public class Scratch {
       public static void main(String[] args) {
            Vertx vertx = Vertx.vertx();
            Oauth2Credentials credentials = new Oauth2Credentials();
            credentials.setCode("someCode");
            credentials.setRedirectUri("some.uri");
            credentials.setFlow(OAuth2FlowType.AUTH_CODE);
    
            OAuth2Auth oAuth2Auth = OAuth2Auth.create(vertx);
    
            oAuth2Auth.rxAuthenticate(credentials); //compile error
        }
}
```

**Comment by jjasper714** [comment]
Just a note that this appears to still be a problem in 5.0.0.CR3

**Comment by vietj** [comment]
thanks for reporting, this it should be fixed in the next release
