### ISSUE TITLE
Variant of RxHelper.unmarhsaller that can use a custom mapper

### ISSUE THREAD

**Issue by bjartek** [vert-x3/vertx-rx#34]
We use jackson-dataformat-yaml in order to unmarshall YAML content to a POJO. It would be very nice if the unmarshaller had a variant that allowed for sending in a mapper, and delegate that mapper to the relevant operator. 

I can give a stab at implementing this and sending a PR if that is ok. It should really not be that hard.

**Comment by vietj** [comment]
@bjartek any contribution ?

**Comment by bjartek** [comment]
This has somehow been forgotten. I will try to contribute it soon.

**Comment by vietj** [comment]
done in 3.5.1, this issue should have been closed
