### ISSUE TITLE
Current Rx api for HttpClient is not composable with idiomatic RxJava

### ISSUE THREAD

**Issue by chefhoobajoob** [vert-x3/vertx-rx#39]
It's a common practice to strive for composable RxJava operator chains that might look something like this:

```
void someFunction(JsonObject theData) {
   Observable.just(theData)
      .flatMap( json -> getSomeObject( json )  )
      .flatMap( someObject -> transformSomeObject(someObject) )
      .subscribe (
         transformed -> { handleTransformedObject( transformed ) },
         error -> { handleError(error) }
      );
}

Observable<SomeClass> getSomeObject(JsonObject theData) {
   return Observable.just( theData )
          .flatMap( theData -> { /* issue http request, emit response observable */ } )
          .flatMap( httpResponse -> { /* emit response body observable */ } )
          .flatMap( responseBody -> { /* emit SomeClass observable */ } );
}

...other functions
```

Calls to `getSomeObject()` could then be used in any chain where retrieval of a `SomeClass` observable is needed, given an input `JsonObject`, and the chain author does not need to know anything about how the instance of `SomeClass` was obtained.

The implementation of `getSomeObject` above can't be realized with the current Rx api for the HttpClient, because it requires a call to `HttpRequest.end()` to be placed outside the operator chain, after the call to subscribe.

This issue is to request that a more RX-idiomatic api for the HttpClient be considered so it can fit more naturally into RxJava-oriented applications.

**Comment by Mart-Bogdan** [comment]
Damn this s***  I was fighting code for few hours thinking what's wrong, and it's seems that vertx-rx is broken (

**Comment by vietj** [comment]
we are aware of this and the `RxHelper#get` can help you achieve this:

http://vertx.io/docs/apidocs/io/vertx/rxjava/core/RxHelper.html#get-io.vertx.rxjava.core.http.HttpClient-int-java.lang.String-java.lang.String-

**Comment by vietj** [comment]
ideally we should have an `HttpClient#getNow(..., Handler<AsyncResult<HttpClientResponse>>)`

perhaps that we can provide a new version of this method that does that in HttpClient.

**Comment by Mart-Bogdan** [comment]
I've tryed tihis

```java

        HttpClientRequest req= httpClient.getAbs("https://api.aps.skype.com/v1/.well-known/openidconfiguration");
        // Status code check and -> Observable<Buffer>
        req.toObservable().
        flatMap(resp -> {
            if (resp.statusCode() != 200) {
                throw new RuntimeException("Wrong status code " + resp.statusCode());
            }
            return Observable.just(Buffer.buffer()).mergeWith(resp.toObservable());
        }).

                // Reduce all buffers in a single buffer
                        reduce(Buffer::appendBuffer).
                // Turn in to a string
                        map(buffer -> buffer.toString("UTF-8"))
                .map((buffer) -> buffer.toString())
                .flatMap(RxUtil.deserializeHelper(OpenIdMetadata.class))
                .subscribeOn(scheduler).observeOn(scheduler)
                .flatMap(meta -> RxUtil.getAbs(httpClient,meta.getJwksUri()))
                .subscribeOn(scheduler).observeOn(scheduler)
                .flatMap(resp-> RxUtil.wrapInObservable(resp::bodyHandler))
                .subscribeOn(scheduler)
                .map(Buffer::toString)
                .subscribeOn(scheduler)
                .flatMap(RxUtil.deserializeHelper(SigningKeys.class))
                .subscribeOn(scheduler)
                .subscribe(keys ->{  ..... });
        req.end();
````

Both tryed `RxHelper#get` and `req.toObservable()` (which is used inside RxHelper) and had same result.
First callback from `Observable#flatMap` was called, but wasn't propagated further

Then I used my own wrapper with **java.util.concurrent.CompletableFuture**

```
     CompletableFuture<Void> chain = getAbs(httpClient, URL_WELL_KNOWN_OPENIDCONFIGURATION)
                .thenCompose(resp -> wrapToFuture(resp::bodyHandler, resp::exceptionHandler))
                .thenApply(Buffer::toString)
                .thenCompose(deserializeHelper(OpenIdMetadata.class))
                .thenCompose(meta -> getAbs(httpClient, meta.getJwksUri()))
                .thenCompose(resp -> wrapToFuture(resp::bodyHandler, resp::exceptionHandler))
                .thenApply(Buffer::toString)
                .thenCompose(deserializeHelper(SigningKeys.class))
                .thenCompose((keys) ->{ .... })

```
```java
    public static <T> CompletableFuture<T> wrapToFuture(Handler<Handler<T>> call, Handler<Handler<Throwable>> errHandler){
        CompletableFuture<T> future = new CompletableFuture<>();
        call.handle(future::complete);
        errHandler.handle(future::completeExceptionally);
        return future;
    }

    public static CompletableFuture<HttpClientResponse> getAbs(HttpClient client, String absoluteURI) {
        CompletableFuture<HttpClientResponse> future = new CompletableFuture<>();

        HttpClientRequest req = client.getAbs(absoluteURI);
        req.exceptionHandler(err -> future.completeExceptionally((err)));
        req.handler(future::complete);
        req.end();

        return future;
    }
```
and it works like charm!

It's seems that **CompletableFuture** can handle this operation OOTB(out of the box), and handle even better than Rx. 
All callbacks are called from same thread that initial Future was fulfilled.

As I see problem with Rx is that it pump out events and flatMap ones aren't get subscribed, or perhaps method chain gets GCed.


Further benefit of using ObservableFuture is that it holds value (or exception) inside of it, and if you call thenApply on already fulfilled future, you get your callback called at once, RxHelper.get would issue new HTTP request in this case.

**Comment by vietj** [comment]
working on it - see vertx-dev google group

**Comment by vietj** [comment]
now the WebClient provides an idiomatic API, so closing this issue
