### ISSUE TITLE
missing deployment methods on io.vertx.rxjava.core.Vertx

### ISSUE THREAD

**Issue by michaelom** [vert-x3/vertx-rx#4]
Some important methods on the Vertx object are gone:

`public Observable<String> deployVerticleObservable(String name, DeploymentOptions options)`
used to be present in earlier versions. Same for the undeploy-variant of this method.

The current workaround involves getting a reference to the Vertx-delegate and use `  void deployVerticle(String name, DeploymentOptions options, Handler<AsyncResult<String>> completionHandler);
` with an ObservableFuture as the third parameter. 

These workaround gymnastics are painful.

**Comment by purplefox** [comment]
Not sure where you are looking but they seem to be all there:

https://vertx.ci.cloudbees.com/view/vert.x-3/job/vert.x3-website/ws/target/site/docs/apidocs/io/vertx/rxjava/core/Vertx.html#deployVerticleObservable-java.lang.String-

**Comment by michaelom** [comment]
Hi Tim,

`public rx.Observable<String> deployVerticleObservable(String name)` is part of the API, but
`public rx.Observable<String> deployVerticleObservable(String name, DeploymentOptions options)` isn't.

Same for undeploy.

**Comment by vietj** [comment]
it is there in milestone 3 : http://vert-x3.github.io/docs/apidocs/io/vertx/rxjava/core/Vertx.html#deployVerticleObservable-java.lang.String-io.vertx.core.DeploymentOptions-

**Comment by vietj** [comment]
same here : https://vertx.ci.cloudbees.com/view/vert.x-3/job/vert.x3-rx/ws/rx-java/target/generated-sources/annotations/io/vertx/rxjva/core/Vertx.java

**Comment by michaelom** [comment]
great. Thank you.
