### ISSUE TITLE
Premature disposal of HTTP client response handlers

### ISSUE THREAD

**Issue by meshuga** [vert-x3/vertx-rx#41]
There's a bug in vert.x RxJava integration which hangs the requests from being processed. It happens when both `io.vertx.rxjava.core.http.HttpClientRequest#toObservable()` and `io.vertx.rxjava.core.http.HttpClientResponse#toObservable()` are being used.

When a response is processed, `io.vertx.core.http.impl.HttpClientRequestImpl#handleResponse(HttpClientResponseImpl)` is used to call two handlers:
- `respHandler` which sets up `HttpClientResponseImpl#handler` and `HttpClientResponseImpl#endHandler` through `ReadStreamAdapter#onSubscribed()` method
- `endHandler` which removes `HttpClientResponseImpl#handler` and `HttpClientResponseImpl#endHandler` through `ReadStreamAdapter#onUnsubscribed()` method

`ReadStreamAdapter` described above have `adapter` property value set to an instance of `HttpClientResponse`.

Reproduction of a bug: https://github.com/meshuga/vertx-rx-bug.

As for now, I just use the code below instead of `io.vertx.rxjava.core.http.HttpClientRequest#toObservable()`:

``` java
AsyncSubject<HttpClientResponse> subject = AsyncSubject.create();
HttpClientRequest req = makeRequest(...);

req.handler(resp -> {
  subject.onNext(resp);
  subject.onCompleted();
});
req.exceptionHandler(subject::onError);
```

I don't know why `ReadStreamAdapter` had been implemented, however I would recommend changing it to plain Rx subjects, that is `AsyncSubject` and `PublishSubject` (less pain).

**Comment by vietj** [comment]
people should use the `WebClient` with RxJava instead
