### ISSUE TITLE
Unnecessary wrapping of handlers while invoking setters on delegate

### ISSUE THREAD

**Issue by techpavan** [vert-x3/vertx-rx#42]
Issue was originally created at: https://github.com/eclipse/vert.x/issues/1463 - Moving to vertx-rx repository.

While consuming vertx-rx-java, I see that handlers set on delegate are wrapped objects of input parameters. This seems to pose two issues -
1. The input parameters in rxjava as well as core packages are of io.vertx.core.Handler type. Still, in rxjava package, we wrap it to the same type through constructor before passing it to delegate. This creates unnecessary objects.
2. If null is passed as a parameter to rxjava package, it results in NPE in core package.

Example:
io.vertx.rxjava.core.http.HttpServerResponse#drainHandler, closeHandler

```

  public HttpServerResponse drainHandler(Handler<Void> handler) { 
    ((io.vertx.core.http.HttpServerResponse) delegate).drainHandler(new Handler<java.lang.Void>() {
      public void handle(java.lang.Void event) {
        handler.handle(event);
      }
    });
    return this;
  }
```

My use case expects to wait for some data to arrive from an external source and write it to client. I register to drain handler when I have excess amount of data and write queue gets full. When I do not have data to write (as I wait for my source to send some), drain events make no sense and I unregister by setting drain handler to null. Though my overall functionality is not impacted, there are NPEs thrown from vertx and additional objects are created.

**Comment by techpavan** [comment]
@vietj Thanks for the fix, verified from the latest. As commented in the other issue, for other types like Buffer, can't we have a null check before creating a new handler object?

**Comment by vietj** [comment]
can you copy/paste an example of code here ? (simpler to see)

**Comment by techpavan** [comment]
Here it is. From io.vertx.rxjava.core.http.HttpServerRequest - 

```
  public HttpServerRequest handler(Handler<Buffer> handler) { 
    ((io.vertx.core.http.HttpServerRequest) delegate).handler(new Handler<io.vertx.core.buffer.Buffer>() {
      public void handle(io.vertx.core.buffer.Buffer event) {
        handler.handle(Buffer.newInstance(event));
      }
    });
    return this;
  }
```
