### ISSUE TITLE
Provide CharSequence API for RoutingContext headers

### ISSUE THREAD

**Issue by itaied246** [vert-x3/vertx-rx#51]
In `RxJava` `RoutingContext` object there is no function that accepts `CharSequence` objects.  
For example, on the normal version for vertx-web:

```
routingContext.request().getHeader(HttpHeaders.AUTHORIZATION); 
```

Would work, while in the rx version:

```
routingContext.request().getHeader(HttpHeaders.AUTHORIZATION.toString()); 
```

The same issue is true for `MultiMap#add`.

**Comment by vietj** [comment]
it happens because the `CharSequence` type is not supported by the code generator.

**Comment by vietj** [comment]
the corresponding methods are thus annotated with `@GenIgnore`
