### ISSUE TITLE
io.vertx.rxjava.core.http.HttpClientResponse#bodyHandlerObservable

### ISSUE THREAD

**Issue by tokuhirom** [vert-x3/vertx-rx#62]
I want to write the code like following:

```
response.bodyHandlerObservable().map(buffer::toString).subscribe(
  System.out::println
);
```

**Comment by tsegismont** [comment]
It's not possible with the `HttpClient`. I believe you could get what you're looking for with the [Web Client](https://vertx.io/docs/vertx-web-client/java/#_rxjava_api)
