### ISSUE TITLE
Missing io.vertx.rxjava.core.buffer.Buffer#getBytes()

### ISSUE THREAD

**Issue by tokuhirom** [vert-x3/vertx-rx#63]
I want to use io.vertx.rxjava.core.buffer.Buffer#getBytes()

**Comment by tsegismont** [comment]
This is not a bug. You can call `getBytes` on the underlying Vert.x Core `Buffer` though:
`rxBuffer.getDelegate().getBytes()`

**Comment by tokuhirom** [comment]
Yes. I know. But I want to use convenient method……
