### ISSUE TITLE
Passing null instead of parameter

### ISSUE THREAD

**Issue by cescoffier** [vert-x3/vertx-rx#71]
When a method passes a Class parameter, the RX generated class passes `null` to the delegated method:

If you have this method:

```
<T> T dumb(Class<T> tClass);
```

It generates:

```
public <T> T dumb(Class<T> tClass) { 
    T ret = (T) delegate.dumb(null);
    return ret;
  }
```

As you can imagine it's a bit annoying...

The culprit is: vertx-rxjava/template/common.templ line 125:

```
...
    return 'null';
}
```

Instead of 
```
    return expr;
}
```

This bug is blocking https://github.com/vert-x3/vertx-service-discovery/issues/14.

**Comment by vietj** [comment]
looks easy to fix :-)

**Comment by cescoffier** [comment]
Yes, I've opened the issue because I wonder if we need to add a test in the CodeGen TCK or just in RX?

It works in JavaScript.

**Comment by vietj** [comment]
I think the method exists in TCK, but the TCK coverage in Rx is incomplete.
