### ISSUE TITLE
Is it possible to using vertx-rx with kotlin language?

### ISSUE THREAD

**Issue by netroby** [vert-x3/vertx-rx#85]
Is it possible to using vertx-rx with kotlin language?
would you please add kotlin support?
https://github.com/ReactiveX/RxKotlin

**Comment by vietj** [comment]
I believe it should be possible.

**Comment by netroby** [comment]
would you please add kotlin support for vertx-rx ? there only rx-java , rx-js, rx-groovy

**Comment by vietj** [comment]
@netroby I think that both Groovy and Kotlin can use fine rx-java today and we will likely deprecate rx-groovy as there is not much value in it. What do you think is missing for Kotlin ?
