### ISSUE TITLE
Return a file as response 

### ISSUE THREAD

**Issue by ashwanikumar04** [vert-x3/vertx-rx#90]
Hello,
I am trying to return a file/image in the response of a get call.

imports
```
import io.vertx.rxjava.core.buffer.Buffer;
import io.vertx.rxjava.core.http.HttpServerResponse;
```
Following is the method which is used to return a byte [] (image or file)

```
public static void respond(byte[] byteArray, HttpServerResponse response, int code, String contentType) {
        Buffer buffer = Buffer.buffer(byteArray);///This give compilation error. No Suitable method found.
        response.putHeader("Content-Type",contentType);
        response.setStatusCode(code);
        response
                .putHeader("Content-Length", String.valueOf(buffer.length()))
                .write(buffer)
                .end();

    }
```

What is the problem? Is there any other way of achieving this?

Thanks

**Comment by tsegismont** [comment]
io.vertx.rxjava.core.buffer.Buffer does not have a #buffer(byte[]) method

If you want an instance create from a byte array, you must create a raw
buffer first and then wrap it:

io.vertx.rxjava.core.buffer.Buffer.newInstance(io.vertx.core.buffer.Buffer(byteArray));

Please ask usage questions in the Vert.x user forum. Not everyone in the
community watches this repo.

2017-04-12 14:41 GMT+02:00 Ashwani Kumar <notifications@github.com>:
