### ISSUE TITLE
rxjava2 branch missing io.vertx.rxjava2.core

### ISSUE THREAD

**Issue by AshleyByeUK** [vert-x3/vertx-rx#94]
Is the RxJava2 branch supposed to be missing the core package? Or should I be importing both vertx-rxjava and vertx-rxjava2?

**Comment by vietj** [comment]
the package is `io.vertx.reactivex.core` for the moment, it should be in the rxjava2 module of the rxjava2 branch

**Comment by AshleyByeUK** [comment]
I probably should have been more specific. I'm trying to go through the vertx-rxjava examples as a first starting point, but can't get an `AbstractVerticle` from vertx-rxjava2.

**Comment by vietj** [comment]
there are no examples yet of rxjava2, you should checkout the rxjava2 branch and look into the rxjava2 folder

**Comment by vietj** [comment]
there is not yet an AbstractVerticle for deploying rxjava2 verticles, you need to wrap yourself the Vertx instance, I will try to add one soon

**Comment by vietj** [comment]
@AshleyByeUK the `io.vertx.reactivex.core.AbstractVerticle` class has been added, it should behave like the rxjava verticle
