### ISSUE TITLE
RxJava2 support

### ISSUE THREAD

**Issue by vietj** [vert-x3/vertx-rx#95]
- [X] API generation
- [X] AbstractVerticle deployment
- [X] extra type support (`Flowable`, `Maybe`)
- [x] `ContextScheduler` support
- [x]  documentation

Branch to build:
- https://github.com/vert-x3/vertx-codegen/tree/type-use-fix
- https://github.com/vert-x3/vertx-rx/tree/rxjava2

**Comment by SercanKaraoglu** [comment]
This may be helpful https://github.com/vert-x3/vertx-rx/pull/67

**Comment by vietj** [comment]
done
