### ISSUE TITLE
SubscribeOn mechanism

### ISSUE THREAD

**Issue by IgorPerikov** [vert-x3/vertx-rx#96]
Hi. In [this book](https://developers.redhat.com/promotions/building-reactive-microservices-in-java/) I saw a lot of examples like this ![screenshot from 2017-07-15 20-42-47](https://user-images.githubusercontent.com/5383314/28241493-4907dd72-699e-11e7-9a93-e68e94974ff5.png)
that says that we have to use event-loop thread for IO operations. But we only have 1 or 2 event loop threads binded to verticle, even if the IO operation would take 100ms, verticle itself will handle silly 10-20 rps. Am I missing something? I don't understand why should I use `RxHelper.scheduler()` instead of `Schedulers.io()`

**Comment by alexlehm** [comment]
the IO operation may take some time but that will not consume time in the verticle thread as this is done async. The only time spent in the thread is whatever is needed for the calculation that the verticle does

**Comment by IgorPerikov** [comment]
And if verticle making any long calculations itself in subscribe section  - I have to use `RxHelper.blockingScheduler()` for them, right? Should I juggle with schedulers like this?
```
webClient.get("/path")
     .rxSend()
     .observeOn(RxHelper.scheduler(vertx))
     .map(HttpResponse::bodyAsJsonObject)
     .observeOn(RxHelper.blockingScheduler(vertx))
     .subscribe(entries -> {
         // some long blocking calculation
     });
```
