### ISSUE TITLE
Rxified RxHelper is missing methods

### ISSUE THREAD

**Issue by MartinNowak** [vert-x3/vertx-rx#98]
The Rxified io.vertx.rxjava.core.RxHelper is missing various methods, e.g. [`ReadStream<T> toReadStream(rx.Observable<T> observable)`](http://vertx.io/docs/apidocs/io/vertx/rx/java/RxHelper.html#toReadStream-rx.Observable-).
That's somewhat impractical as using the non-rxified io.vertx.rx.java.RxHelper forces you to mix rxified with non-rxified classes, e.g. you need a non-rxified Pump to work with the ReadStream, but in an rxified Router/HttpServerRequest the response is an rxified WriteStream.
Any suggestions on how to best resolve such issues?

**Comment by tsegismont** [comment]
Would you mind to contribute them?

2017-07-27 12:20 GMT+02:00 Martin Nowak <notifications@github.com>:

**Comment by MartinNowak** [comment]
Turns out that `Pump.pump(Observable, WriteStream)` is directly supported, might be the reason why the rxified helper needs no `Observable -> ReadStream` conversion.

**Comment by vietj** [comment]
@maeste yes that's the point

**Comment by vietj** [comment]
that being said as note: I thought at some point to make class that extends WriteStream<T> to have a `Observer<T> toObserver()` method.
